name: Cron

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Execute
        run: php ./publish.php ${{ secrets.X_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
